// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUtWtQfsMlfzTm7kJXqxa6jMGg27vp0Cg',
    appId: '1:467105409973:web:2d41bc6adca2559f8d47fc',
    messagingSenderId: '467105409973',
    projectId: 'health-helper-f47cd',
    authDomain: 'health-helper-f47cd.firebaseapp.com',
    storageBucket: 'health-helper-f47cd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOfq3NAqvRfJOAl0CPZe8ujsmOxdlDDEU',
    appId: '1:467105409973:android:68b0862c2d5eb3dc8d47fc',
    messagingSenderId: '467105409973',
    projectId: 'health-helper-f47cd',
    storageBucket: 'health-helper-f47cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd8OXqkPJY1Eji3D9OErw10gFnxwBv4uM',
    appId: '1:467105409973:ios:fda07211322581da8d47fc',
    messagingSenderId: '467105409973',
    projectId: 'health-helper-f47cd',
    storageBucket: 'health-helper-f47cd.appspot.com',
    iosClientId: '467105409973-kckl4auh5hs0r9qifke0eu3r05morrri.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthHelper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUtWtQfsMlfzTm7kJXqxa6jMGg27vp0Cg',
    appId: '1:467105409973:web:3e6ee5c74f7737868d47fc',
    messagingSenderId: '467105409973',
    projectId: 'health-helper-f47cd',
    authDomain: 'health-helper-f47cd.firebaseapp.com',
    storageBucket: 'health-helper-f47cd.appspot.com',
  );
}
